=for comment This file is shared by both README.pod and Perl.pm
after its __END__ It might also be on github:
https://github.com/rocky/p5-Term-ReadLine-Perl5

=begin html

<img src="https://travis-ci.org/rocky/p5-Term-ReadLine-Perl5.png">

=end html

=head1 NAME

Term::ReadLine::Perl5 - A pure Perl implementation GNU Readline

=head1 SYNOPSIS

  use Term::ReadLine::Perl5;
  $term = new Term::ReadLine::Perl5 'ProgramName';
  while ( defined ($_ = $term->readline('prompt>')) ) {
    ...
  }

=head1 DESCRIPTION

=head2 Overview

This is a implementation of the GNU Readline/History Library written
entirely in Perl.

GNU Readline reads lines from an interactive terminal with I<emacs> or
I<vi> editing capabilities. It provides as mechanism for saving
history of previous input.

This package typically used in command-line interfaces and REPLs (Read,
Eval, Print Loops).

=head1 INSTALL

To install this module type:

    perl Makefile.PL
    make
    # for interactive testing:
    make test
    # for non-interactive testing
    AUTOMATED_TESTING=1 make test
    make install # might need sudo make install


For interactive testing try redirect I<STDIN> and/or I<STDOUT>.

=head1 LICENSE

See the contents of LICENSE

=cut
