=begin html

<a href="https://travis-ci.org/rocky/p5-Term-ReadLine-Perl5"><img src="https://travis-ci.org/rocky/p5-Term-ReadLine-Perl5.png"></a>

=end html

=head1 NAME

Term::ReadLine::Perl5 - A Perl5 implementation GNU Readline

=head1 SYNOPSIS

  use Term::ReadLine::Perl5;
  $term = new Term::ReadLine::Perl5 'ProgramName';
  while ( defined ($_ = $term->readline('prompt>')) ) {
    ...
  }

=head1 DESCRIPTION

=head2 Overview

This is a implementation of the GNU Readline/History Library written
in Perl5.

GNU Readline reads lines from an interactive terminal with I<emacs> or
I<vi> editing capabilities. It provides as mechanism for saving
history of previous input.

This package typically used in command-line interfaces and REPLs (Read,
Eval, Print, Loop).

=head1 INSTALL

To install this module type:

    perl Build.PL
    make
    # for interactive testing:
    make test
    # for non-interactive testing
    AUTOMATED_TESTING=1 make test
    make install # might need sudo make install


For interactive testing try redirect I<STDIN> and/or I<STDOUT>.

If you see something like:

    Can't ioctl TIOCGETP: Invalid argument at ...

install L<Term::ReadKey>

=head1 HISTORY

The first implementation was in Perl4 (mostly) by Jeffrey
Friedl. He referenced FSF the code Roland Schemers F<line_edit.pl>.

Ilya Zakharevich turned this into a Perl5 module called
L<Term::ReadLine::Perl>. Some of the changes he made include using
L<Term::ReadKey> if present, and made this work under I<xterm>. The
file F<Term/ReadLine/Perl5/CHANGES> contains a list of his changes.

=head1 BUGS

Bugs are accepted via Github:
https://github.com/rocky/p5-Term-ReadLine-Perl5/issues

=head1 LICENSE

See the contents of the file LICENSE

=cut
